version = 0.1
[default.deploy.parameters]
stack_name = "aws-sam-ts-template"
resolve_s3 = true
s3_prefix = "aws-sam-ts-template"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
