AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template for Node.js TypeScript Lambda

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs22.x
    Architectures:
      - x86_64

Resources:
  GetAllFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-all
      CodeUri: dist/
      Handler: get-all.handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /get-all
            Method: GET
